### ISSUE TITLE
Redirect behavior should match the HTTP specification

### ISSUE THREAD

**Issue by masumsoft** [olalonde/follow-redirects#12]
As far as I know, not all of the 300-399 http response codes needs to have a redirect. But looking at the code, I found you are redirecting everything in 300-399. Please look at the following url to have a reference:

http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by jamestalmage** [comment]
We are redirecting when the response
  1. has a status code of 300-309  
  **and** 
  2. has a location header.

From your link: 

> If the server has a preferred choice of representation, it SHOULD include the specific URI for that representation in the Location field; user agents MAY use the Location field value for automatic redirection

What we are not taking into account is that we should probably only be redirecting for `GET` and `HEAD` methods.

> If the `[301 | 302 | 307]` status code is received in response to a request other than GET or HEAD, the user agent MUST NOT automatically redirect the request unless it can be confirmed by the user, since this might change the conditions under which the request was issued.

When correcting this, it's probably advisable to include the addition of a `alwaysFollow` flag that will ignore the above spec and continue operating as before. (perhaps the `alwaysFollow` flag should initially default to `true` for backwards compatibility).

**Comment by jamestalmage** [comment]
This is going to be addressed eventually. See #19.

**Comment by jamestalmage** [comment]
I've started the creation of a test suite that logs the redirect behavior across browsers.

See: https://github.com/jamestalmage/browser-redirect-test

**Comment by RubenVerborgh** [comment]
Rather than following what browsers happen to do, let's stick to the HTTP specification, which is what browsers and servers should follow anyway.
