### ISSUE TITLE
Enable Travis Build

### ISSUE THREAD

**Issue by jamestalmage** [olalonde/follow-redirects#17]
@olalonde I've setup travis to automatically run our builds, and added badges for coverage, etc.

Can you head over to [travis-ci.org](https://travis-ci.org/profile/olalonde) and enable support (needs to be you).

Ignore the organization request from earlier, I thought that might have been a way to make it easier for me to maintain Travis stuff for you, but it seems I must be a full owner of the repo to set up travis on it. Other services (Coveralls, david-dm) allowed me to set up services just by being a collaborator, I think leaving it where it is will work fine and still require minimal drains on your time.

**Comment by olalonde** [comment]
Build should be enabled now. Just tested with a push. https://travis-ci.org/olalonde/follow-redirects

**Comment by jamestalmage** [comment]
:+1:
