### ISSUE TITLE
Create optimal cross-platform development experience via browserify.

### ISSUE THREAD

**Issue by jamestalmage** [olalonde/follow-redirects#19]
I think `follow-redirects` _default_ behavior should be to mimic the behavior of the `http` and `https` as used in the browser via `browserify`. `XMLHtppRequest` follows redirects transparently, and there is no way to disable that. Therefore the browserified versions of `http` and `https` automatically have a `follow-redirects` like behavior, but the server side counterparts do not (obviously, there would be little point to this module otherwise). However, this behavior breaks one of the key goals of `browserify`; the ability to write code that behaves identically on the client and server. This isn't the fault of browserify, due to the way `XMLHttpRequest` behaves they can't possibly emulate the behavior of the native modules.

I am definitely *not* suggesting we turn `follow-redirects` into a client side library, but instead help the _server_ behave more like the _client_. This is backwards from the goal of most browserify modules, but as previously stated, it's just not possible to emulate the server in this case. Developers seeking to create a cross platform solution would use `follow-redirects` on the server, and have browserify automatically swap it out with `browserify-http` when creating the client bundle. Indeed, I have already detailed instructions for doing just that in the README.

We are already very close. For many scenarios the library will work as is. However, there are still a few points to be addressed.

 1. Issue #12 needs to be fixed. Specifically, our current logic for deciding when to redirect is pretty basic. It's not always OK to redirect for every `300` level code. The [spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) notes many scenarios where typical browser behavior is actually not to spec. Rather than strictly conforming to the spec, we should follow whatever the most common behavior is. 
 2. Also related to #12, we currently always perform a `GET` on redirection, even if the original request was a `POST` or otherwise. This is the correct response in most situations, but (I believe) not all. 
 3. Handling errors. Currently we emit an error on the returned client request object if we exceed the maximum number of redirects. We also forward any errors we encounter on subsequent redirected requests to the original one.  If we encounter a `3XX` status code without a `Location` header, we do not throw an error, but return the result to the registered callback. This all makes logical sense, but we should work to make our behavior the same as the client side modules.
 4. Make all this configurable. There is already an (optional and as yet undocumented) `makeRequest` callback that allows us to change these behaviors on master. It's probably wise to keep a "legacy" version of that callback around that continues to mimic the behavior of the library as it has existed for years.
 5. We should do all this while still maintaining API compatibility with the core modules (nodes native `http` and `browserify-http`, etc). Plenty of cross-platorm options exist if you are willing to deal with a different API. The goal here should be an easy transitions for those using the core modules.
 6. Be as lightweight on the client side as possible. Ideally, this means not existing at all on the client, and instead differing to the core `browserify` implementations that are likely already bundled.

**Comment by bendrucker** [comment]
I like this. I personally use https://github.com/sindresorhus/got quite heavily and it follows redirects. But it's not 100% identical when browserified and I think there's room for a module that is and sits at a lower level.

**Comment by RubenVerborgh** [comment]
> Issue #12 needs to be fixed.

Done.

> Also related to #12, we currently always perform a GET on redirection, even if the original request was a POST or otherwise. This is the correct response in most situations, but (I believe) not all.

Done.

> If we encounter a 3XX status code without a Location header, we do not throw an error, but return the result to the registered callback.

This is in accordance with the HTTP spec, so I wouldn't change.

> Make all this configurable. 

I opted to make the library more simple instead. It only performs redirects, and this behavior can be switched off by setting the `followRedirects` option to false.

> We should do all this while still maintaining API compatibility with the core modules (nodes native http and browserify-http, etc).

Check.

> Be as lightweight on the client side as possible.

Check.
