### ISSUE TITLE
Implement `request.setTimeout`.

### ISSUE THREAD

**Issue by BenasPaulikas** [olalonde/follow-redirects#25]

**Comment by jamestalmage** [comment]
It's probably a good idea to implement [`request.setTimeout()`](https://nodejs.org/api/http.html#http_request_settimeout_timeout_callback) for feature parity.

**Comment by jamestalmage** [comment]
@olalonde 
Can you add a `feature-parity` label, for use on these types of issues where we are missing a feature from the core library.

**Comment by olalonde** [comment]
Sure, just created the tag.

**Comment by olalonde** [comment]
I wonder if another approach would be to use es6 classes to extend the native modules. I haven't touched this code in a while so you know it better than me, just throwing the idea.

**Comment by jamestalmage** [comment]
I'm trying to maintain compatibility with all LTS versions of Node for now.
