### ISSUE TITLE
Use same request method when following 307 status

### ISSUE THREAD

**Issue by fnando** [olalonde/follow-redirects#27]
As per RFC:

> **307 Temporary Redirect**
>
> The 307 (Temporary Redirect) status code indicates that the target resource resides temporarily under a different URI and the user agent MUST NOT change the request method if it performs an automatic redirection to that URI.  Since the redirection can change over time, the client ought to continue using the original effective request URI for future requests.
> 
> The server SHOULD generate a Location header field in the response containing a URI reference for the different URI.  The user agent MAY use the Location field value for automatic redirection.  The server's response payload usually contains a short hypertext note with a hyperlink to the different URI(s).
>
> Note: This status code is similar to 302 (Found), except that it does not allow changing the request method from POST to GET.  This specification defines no equivalent counterpart for 301 (Moved Permanently) ([RFC7238], however, defines the status code 308 (Permanent Redirect) for this purpose).

Right now `GET` is [always being used](https://github.com/olalonde/follow-redirects/blob/master/create.js#L73-L74).

```js
function defaultMakeRequest(options, cb, res) {
  if (res) {
    // This is a redirect, so use only GET methods
    options.method = 'GET';
  }

  var req = options.nativeProtocol.request(options, cb);

  if (res) {
    // We leave the user to call `end` on the first request
    req.end();
  }

  return req;
}
```

**Comment by fnando** [comment]
@olalonde sorry to bug you about this, but it'd be awesome if you merge this and release a new version. I'm having a problem with axios because follow-redirects cannot be disabled (https://github.com/mzabriskie/axios/issues/211) and the redirection is being followed with wrong request method.

**Comment by olalonde** [comment]
Thans for the PR. @jamestalmage is pretty much maintaining this module these days so I'd like to let him do the merge/release. If he doesn't show a sign of life by tomorrow, I'll do it (and feel free to bug me again if I forget :)).

**Comment by fnando** [comment]
ping @jamestalmage. Can you merge this, please?

**Comment by jamestalmage** [comment]
Hi. I'm just back from two weeks abroad. It may take me to the weekend to handle this. Sorry for the delay.

**Comment by fnando** [comment]
@jamestalmage can you please merge and release a new version?
