### ISSUE TITLE
Help required for Redirect URL to return response.headers when the status code is 302

### ISSUE THREAD

**Issue by Brad19** [olalonde/follow-redirects#29]
Hi, 
I was googling about an issue which i'm facing at my end about the Redirect URL and found your blog "http://syskall.com/how-to-follow-http-redirects-in-node-dot-js/" . Indeed it is an useful blog. However the problem at my end was

When I use the API end points manually with Postman (with interceptors turned ON) along with body and headers, I was able to get 302 redirects. However for my API Automation testing purpose I thought of using

request() // npm request

which is as follows. But always I get the response as 500. My objective of my test is to get the response.headers when I get the status code as 302 from response. Can you pls throw some light and provide me some direction as I got struck on this

request(
url : 'https://blah/blah'
client_id :'something.com.au'
redirect_uri :'http://something' // this is a dummy one as it is not required for mobile app
response_type :'code'
scope : 'ALLAPI'
Username : 'cxxx'
Password : 'ccxcxc'
headers : {
    'Content-Type': 'application/x-www-form-urlencoded',
    'followRedirect' : true
}
Thanks,
Brad

**Comment by jamestalmage** [comment]
This seems like a question for the folks over at `request`, which is an entirely separate module.
