### ISSUE TITLE
When no redirect happened fetchedUrls[0] only contains protocol + hostname

### ISSUE THREAD

**Issue by pietercolpaert** [olalonde/follow-redirects#32]
When no redirect happens, we would expect response.fetchedUrls[0] to contain the full URL for the request that was just executed. However, it only contains the protocol + the hostname.

**Comment by jamestalmage** [comment]
Sounds good to me. Should it be a string URL or parsed URL object?

**Comment by pietercolpaert** [comment]
a string URL: similar as what would happen when `response.fetchedUrls.length > 1` :)

**Comment by jamestalmage** [comment]
👍 - Want to do a PR?

**Comment by pietercolpaert** [comment]
I'm overcommitted at this moment. I thought I'd just register it as an issue for now for anyone else to fix it at this time :)

**Comment by RubenVerborgh** [comment]
`fetchedUrls` (array) is now `responseUrl` (string), so this issue does not occur anymore.
