### ISSUE TITLE
Buffer request bodies?

### ISSUE THREAD

**Issue by jamestalmage** [olalonde/follow-redirects#35]
Looking at the HTTP spec, I think it is entirely possible that the server will consume at least part of the request body before issuing a `307` redirect. When that happens, we are unable to redirect because whatever portion of the stream has been consumed is lost to us.

Perhaps we should buffer the request body when it's a stream (at least to a point).

**Comment by RubenVerborgh** [comment]
> it is entirely possible that the server will consume at least part of the request body before issuing a 307 redirect

Seems like a rather theoretical possibility; I have never encountered this behavior with any server before. I therefore propose to close this until a real-world case comes up.

**Comment by cwharris** [comment]
Could this be why cookies issued in a 3** response are not included in the next request?

**Comment by RubenVerborgh** [comment]
No, cookies are part of the headers, and they are repeated. (And this issue was fixed.) Are you sure this is the case? If so, please open a new issue.
