### ISSUE TITLE
Handle infinite redirects

### ISSUE THREAD

**Issue by IonicaBizau** [olalonde/follow-redirects#41]
According to [this comment](https://github.com/IonicaBizau/scrape-it/issues/28#issuecomment-237825303), we should handle the infinite loops here, in this library.

**Comment by olalonde** [comment]
@IonicaBizau you could set maxRedirects option for now. @jamestalmage any way to detect infinite redirect loops?

**Comment by jamestalmage** [comment]
Hmm. How are infinite loops detected by browsers? Just see if we have already been here before by examining the redirect stack? We already track that stack, so if it really is that simple, it should be fairly easy.

**Comment by IonicaBizau** [comment]
I asked it [here](http://stackoverflow.com/q/38892421/1420197), but didn't get any answers...

**Comment by jamestalmage** [comment]
So, according to [this SO answer](http://stackoverflow.com/questions/6852846/browser-redirect-loop-detection)

Both Chrome and Firefox let you redirect 21 times before failing. There is no fancy loop detection. Just  `maxRedirects = 21`.

**Comment by IonicaBizau** [comment]
@jamestalmage Then, maybe can we set here the `maxRedirects` to be `21` by default?

**Comment by jamestalmage** [comment]
We currently have it defaulted to `5` I believe, which should catch loops sooner, so I'm not sure it would solve your problem.

That said, I guess I'm fine with `21` as the default.

@olalonde - Do you remember why `5` was chosen in the first place?

**Comment by IonicaBizau** [comment]
@jamestalmage That sounds good too, but then why does [this problem](https://github.com/IonicaBizau/scrape-it/issues/28#issuecomment-237825303) appear at all?

What happens after `5` redirects?

**Comment by jamestalmage** [comment]
According to the [test suite](https://github.com/olalonde/follow-redirects/blob/master/test/test-with-server.js#L161-L218), it should produce an error.

**Comment by IonicaBizau** [comment]
@jamestalmage @RubenVerborgh Thanks!
