### ISSUE TITLE
Drop 'Content-Length' after re-assigning method to GET?

### ISSUE THREAD

**Issue by QingYun** [olalonde/follow-redirects#49]
Got some problems on redirecting from a 302 POST request, basically the server refused to send back any response. After some investigation, I found it was caused by the `Content-Length` header, which probably makes the server think it's an invalid GET request.

My current makeshift is deleting the `Content-Length` field from `this._options.headers` for all GET requests inside `_processResponse`. Any better solution?

**Comment by RubenVerborgh** [comment]
Indeed, when changing a `POST` request to `GET`, we should drop the body and its associated headers.

**Comment by RubenVerborgh** [comment]
Thanks for reporting! Fix and released as v1.2.1.
