### ISSUE TITLE
"Bug" when switching methods

### ISSUE THREAD

**Issue by xogeny** [olalonde/follow-redirects#51]
I spent half a day tracking this down.  I'm not sure if this qualifies as a bug, but if you accept my suggested fix, I'll submit a PR.

The problem I was having was that one of my tests on my project was failing (timing out, specifically).  Needless to say, there were many layers above `follow-redirects` to comb through for the error.  But I simply couldn't find anything.  The problem I was seeing was that when my server returned a redirect, my client would hang.  Hitting the server with a browser showed a proper Location header and status code.  But the client (using `axios`) just would not return.  It was making the request and the server was sending back a response, but the promise in Axios was never resolved.  I presumed that the redirect was being processed, but it never seemed to get a response.

So I rolled up my sleeves and tried to track down exactly where the process was breaking down.  My original request was a `POST` and `follow-redirects` was converting that to a `GET`.  That by itself is what I expected, so that was no problem.  I could change my original method to take a `GET` instead and then the problem went away.  So that fixed my problem (tests ran to completion), but it really bugged me that I didn't understand why this wasn't working and I didn't want to just leave it at that and just hope not to run into it again.

It clearly had something to do with redirects, so I turned on debugging output with `DEBUG=follow-redirects` and took a look at what was going on.  I could see `follow-redirects` making the redirect request.  I assumed, incorrectly, that perhaps when a `POST` request was made, the `POST` method was used on the redirect (that would have cause an error).  But that wasn't the issue.  In fact, if that were the case the request should have completed (which wasn't happening).  This provides a subtle clue into what actually was the problem.

I compared the `options` being passed in both the working and non-working cases.  There were only two differences in those requests and they were related to headers.  This is because my original request (which came through `axios` had headers **normally associated with a POST** in them.  Specifically `Content-Type` and `Content-Length`.  When `follow-redirects` switches the method to `GET` in its 307 handling, **it leaves those there**.  So the resulting redirected `GET` request has a `Content-Length` header in it.  Since a `GET` request has no body, this makes no sense.

I noticed that with the Chrome extension DHC, if I make a GET request with a `Content-Length` header, it removes it automatically.  But it appears what is happening is that `follow-redirects`/`http` are keeping that header in there and when it hits the Express server, the express server sits and waits until it gets all the bytes for the body.  But, of course, there is no body.

What I did to fix this was to simply change this:

```
	if (!(this._options.method in safeMethods)) {
		this._options.method = 'GET';
	}
```

...to this...
```
	if (!(this._options.method in safeMethods)) {
		this._options.method = 'GET';
                // Remove a Content-Length header if one is present
		delete this._options.headers["Content-Length"];
	}
```

This seems perfectly reasonable to me and it is very much inline with what DHC does.  But I wanted to first check here to see if a) this seems like a reasonable approach and b) whether you want me to create a PR for this.

I can't see what harm this would do, but you guys know more about the HTTP implications of this than I do.  For that matter, there may be other headers to consider here as well (i.e., that would never apply to a `GET` and therefore should be removed).

**Comment by RubenVerborgh** [comment]
This is exactly what 06195629f8105e222d08e432b9e66d40f34265e9 has been doing since v1.2.1. Which version of follow-redirects are you using?

**Comment by xogeny** [comment]
Doh! I'm using Axios 0.15.3 which uses follow-redirects 1.0.0. I'll try to convince Axios to upgrade. Thanks!

**Comment by RubenVerborgh** [comment]
Axios should just do semver right: it [depends on 1.0.0](https://github.com/mzabriskie/axios/blob/v0.15.3/package.json#L76) instead of ^1.0.0 as it does for other packages. Then you would automatically get the correct version, without API incompatibility.
