### ISSUE TITLE
Object.assign is not a function

### ISSUE THREAD

**Issue by betaWeb** [olalonde/follow-redirects#56]
Hi there,

I use node-rest-client module which uses your module in dependance.
When I wan't to make a HTTP request, it returns an error `Object.assign is not a function` from your module (index.php lines 169 and 134).

My app is under Node 0.10.44 (I can't upgrade).

Please fix it asap (you can find a great polyfill on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill)

**Comment by RubenVerborgh** [comment]
follow-redirects requires Node >= 4.0. I suggest you indeed use the polyfill from MDN.

**Comment by RubenVerborgh** [comment]
0f0cd9ae1c236ff1960ad9cca6fd9e76071f25ad now explicitly lists the required version.

**Comment by RubenVerborgh** [comment]
See also https://github.com/olalonde/follow-redirects/pull/44#issuecomment-250990791.
