### ISSUE TITLE
Agent, cookies, timeout

### ISSUE THREAD

**Issue by voidmonk** [olalonde/follow-redirects#58]
Hi, I had a few questions:

1. If both `agent` (nodejs http/https option) and `agents` (follow-redirects option) are passed, then will the `agent` option be used ever in the main or redirected requests?

2. It seems cookies set with a 302 redirect (i.e. having both `location` and `set-cookie` headers) are not passed over to the following URL? For example, this httpbin test URL: https://httpbin.org/cookies/set?k1=v1&k2=v2 should set two cookies, and do a 302 redirect to https://httpbin.org/cookies, which simply emits the cookie values, but it shows none.

3. Looks like the request timeout is applied per redirection, not as an overall measure, which is somewhat confusing. For example, if timeout is set to 2000 ms, and 5 redirections occurred taking a total of 5000 ms, then no error is thrown, although it should. I think the timeout value (just like the native http/s modules) should be applied to the whole request.

Cheers.

**Comment by RubenVerborgh** [comment]
1. `agent` will be ignored if `agents` is specified

2. That is correct; like the native `http` and `https` modules, _follow-redirects_ does not handle cookies.

3. Tricky question. One the one hand, it would be intuitive that the operation never takes longer than `timeout`. On the other hand, this might lead to unexpected failures. In practice, more than 1 redirect in a sequence will be quite rare, so I expect the impact to be limited.

PS Feel free to create multiple issues next time, then it is easier to follow up what has been handled and what hasn't.

**Comment by voidmonk** [comment]
Thanks.

2. Doesn't the RFC dictate that cookies must be passed to the following request to the same host (as in a redirection)?

**Comment by RubenVerborgh** [comment]
RFC6265 might very well do that, but this library only implements RFC2616.
