### ISSUE TITLE
Redirect history

### ISSUE THREAD

**Issue by stevenvachon** [olalonde/follow-redirects#59]
would be nice. Either add it to the response object or add a second argument to the callback function.

**Comment by RubenVerborgh** [comment]
What use cases do you see for the _full_ history?

We currently [store the final URL in `responseUrl`](https://github.com/olalonde/follow-redirects/blob/v1.2.3/index.js#L150).

**Comment by stevenvachon** [comment]
[broken-link-checker](https://npmjs.com/broken-link-checker) stores the redirect history (currently provided by [bhttp](https://npmjs.com/bhttp)) of each requested URL, among other meta. The use case for this meta would be an SEO UI.

**Comment by RubenVerborgh** [comment]
This seems like a rather specific use case, which I don't think fits a generic drop-in replacement like _follow-redirects_. Probably, a SEO library would also want to maintain the status codes on each redirect, etc.

**Comment by stevenvachon** [comment]
Any project can have a need for a redirect history, depending on its requirements.

The detail level of the redirect history could be controlled through options. For example, a reduced history could contain only the status code and headers per redirect.

**Comment by RubenVerborgh** [comment]
> Any project can have a need for a redirect history, depending on its requirements.

I agree; however, they will then mostly not need a drop-in replacement that performs redirects transparently, but rather something more explicit.

> The detail level of the redirect history could be controlled through options.

That would indeed be necessary; it would be a major overhead to maintain the history by default.

> For example, a reduced history could contain only the status code and headers per redirect

I wouldn't call that “reduced” 😄  It's quite heavy to keep all headers.

But what do you need: just the URLs of all redirects, or more?

**Comment by stevenvachon** [comment]
broken-link-checker currently has a redirect history Array of Objects containing these properties:
* `headers`
* `status`
* `statusText`
* `url`

**Comment by RubenVerborgh** [comment]
I'd be option to a pull request that adds such functionality under a flag.

**Comment by stevenvachon** [comment]
I'm thinking that it could be configured with:
```js
options.redirectHistoryKeys = ['status', 'url'];
```
where the default value is `[]`, meaning no keys are added, which can mean that no redirect history is recorded.

**Comment by RubenVerborgh** [comment]
Not convinced by the above option; it seems too complex.

Perhaps we can simply expose the native responses through a `nativeResponse` event? Then you can track all of these yourself.

**Comment by RubenVerborgh** [comment]
This can be realized using the new [`wrap`](https://github.com/olalonde/follow-redirects#advanced-usage) functionality, which allows you to pass custom `http` and `https` implementations. In these custom implementations, you can track the original request and any other parameters you want.

**Comment by RubenVerborgh** [comment]
Implemented as #86.
