### ISSUE TITLE
Host && Port will be overwritten after running url parsing

### ISSUE THREAD

**Issue by AngryPowman** [olalonde/follow-redirects#60]
An unexpected problem occurred during redirect url parsing:
https://github.com/olalonde/follow-redirects/blame/master/index.js#L145

My definitions as follows :

```
let options = {
    host: 'proxy-host.com',
    port: 8080,
    method: 'GET',
    path: 'http://download.image.com/test.jpg',
    followRedirect: true,
    maxRedirects: 3
 };
```

This problem has led `options.host` and `options.port` failure after running redirect url passing. The new `Host` and `Port` in redirect url will be re-assigned to my options when I am using `Host` and `Port` as a proxy server.

**Comment by vizee** [comment]
It's very helpful to me

**Comment by Sumxx** [comment]
It's very helpful to me

**Comment by ly0** [comment]
It's very helpful to me

**Comment by RubenVerborgh** [comment]
What exactly do you mean with "failure"? It is expected behavior that the host and port change on redirect, as this is how HTTP redirects work.

However, your original object should not be modified.

**Comment by RubenVerborgh** [comment]
> The new Host and Port in redirect url will be re-assigned to my options

Cannot reproduce; seems unlikely because [a new object is created](https://github.com/olalonde/follow-redirects/blob/v1.2.3/index.js#L210).
