### ISSUE TITLE
[Question] Query regarding Fork License

### ISSUE THREAD

**Issue by akhilkedia** [olalonde/follow-redirects#62]
I am making a fork of this project for use with IoTjs (which is like a light version of nodejs for embedded environments).
This fork may be used fo rcommercial purposes.
Going by the LICENSE file in the repo, its is perfectly acceptable for me to do so as long as I keep original LICENSE file right?

**Comment by RubenVerborgh** [comment]
Thanks for asking!

Yes, you can use this code or derivatives for commercial purposes, provided that the [license and copyright notice](https://github.com/olalonde/follow-redirects/blob/master/LICENSE) are included (both in source and compiled distributions).
