### ISSUE TITLE
Design pattern for caching redirected responses

### ISSUE THREAD

**Issue by pietercolpaert** [olalonde/follow-redirects#63]
In the NodeJS framework, I’d like to create a user agent (outside the browser) that also properly implements HTTP client caching. Problem with this library is that it handles redirects itself, and omits the cache in front of follow-redirects.

E.g., in pseudo javascript code:
```javascript
var url = 'http://data.linkeddatafragments.org/bwv/classifications/10'
if (!cache.get(url)) {
    http.get(url, function (...) {
        var url2 = 'http://data.linkeddatafragments.org/bwv?subject=http%3A%2F%2Fdata.linkeddatafragments.org%2Fbwv%2Fclassifications%2F10';
        if (!cache.get(url2)) {
             http.get(url2);
        }
    });
}
```
This example will twice download the exact same page while the cached response should be given.

### 1. A flag

When the flag is set, the library will not automatically follow redirects, but will also allow for returning the new location URL, for which an external cache can then check what to do: resolve the promise, or again request it via follow-redirects.

### 2. Also implement an (in-memory) caching system in follow-redirects

Also allow a cache instance to be given to the follow-redirects library.

### 3. Document how follow-redirects can be used as one part of the chain

Inspired by express middleware design pattern, we could also document chaining HTTP request libraries, in which you can put caches behind follow-redirects without issues.

**Comment by RubenVerborgh** [comment]
> 1. A flag

> the library will not automatically follow redirects, but will also allow for returning the new location URL

Seems too weird/confusing.

> 2. Also implement an (in-memory) caching system in follow-redirects

Possible, but perhaps best avoided to keep follow-redirects specialized enough.

> 3. Document how follow-redirects can be used as one part of the chain

follow-redirects cannot be used in a decorator pattern straight away, as it needs access to `http` and `https` internally.

----

How about the following?
```javascript
const followRedirects = require('follow-redirects').wrap({
    http: require('your-custom-http'),
    https: require('your-custom-https'),
});
```

**Comment by pietercolpaert** [comment]
Looks good and would resolve my issue! Can we implement this?

**Comment by RubenVerborgh** [comment]
Yes we can!

**Comment by RubenVerborgh** [comment]
Could you please test https://github.com/olalonde/follow-redirects/tree/feature/wrap?
