### ISSUE TITLE
does not work with shortners which use meta-refresh

### ISSUE THREAD

**Issue by motleycrew** [olalonde/follow-redirects#64]
Module does not work with shortners which use meta refresh
 http://gee.su/Ctv2n

**Comment by RubenVerborgh** [comment]
That's a problem of gee.su; they should use proper HTTP-level redirects. follow-redirects is a library that operates at the protocol level, not on the content/representation level. Addressing such concerns would require the library to incorporate an HTML parser, which would be many times bigger than this library itself.

Also, the above link “redirects” to `http://www.1.domwebshop.su/You-should-take-a-blue-pill-to-become-a-monster-in-bed.php`…
