### ISSUE TITLE
Content-Type header is dropped

### ISSUE THREAD

**Issue by brendo** [olalonde/follow-redirects#70]
Using `axios`, I discovered this is the underlying library that handles redirects, so 👋 .

The API I'm communicating with follows [JSON API](http://jsonapi.org/format/#content-negotiation-clients) which describes that clients must add `Content-Type: application/vnd.api+json` headers to their requests.

I have noticed though that when performing a redirect, this library will [remove any header that starts with `content-*`](https://github.com/olalonde/follow-redirects/blob/master/index.js#L138-L140).

This results in my requests failing, with a `415 Unsupported Media Type` response (as per spec).

Just wondering what the intentions were behind this? Is there a workaround to "reinsert" headers such as Content-Type later?

Thanks!

**Comment by brendo** [comment]
Looks related to the fix implemented to fix https://github.com/olalonde/follow-redirects/issues/49. Wonder if it can be dialled back to just removing the `Content-Length` header?

**Comment by RubenVerborgh** [comment]
Woops, definitely wrong to drop `Content-Type`. Should drop other things such as encoding etc., not just length.

**Comment by RubenVerborgh** [comment]
No, wait, this is intended behavior.

> I have noticed though that when performing a redirect, this library will remove any header that starts with content-*.

Not correct: only for a 307, where the entity must be dropped.

**Comment by brendo** [comment]
> where the entity must be dropped.

Is that in the spec somewhere? I checked [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.4.3), but didn't find anything that specified that exactly?

**Comment by RubenVerborgh** [comment]
I've [documented this in the source code](https://github.com/olalonde/follow-redirects/blob/v1.2.5/index.js#L124-L130):

> Automatic redirection needs to done with
   care for methods not known to be safe, as defined in Section 4.2.1,
   since the user might not wish to redirect an unsafe request.

— [RFC 7231, $6.4](https://tools.ietf.org/html/rfc7231#section-6.4)

This document further says:

> Early user agents split on whether the
      method applied to the redirect target would be the same as the
      original request or would be rewritten as GET.  Although HTTP
      originally defined the former semantics for 301 and 302 (to match
      its original implementation at CERN), and defined 303 (See Other)
      to match the latter semantics, prevailing practice gradually
      converged on the latter semantics for 301 and 302 as well.  The
      first revision of HTTP/1.1 added 307 (Temporary Redirect) to
      indicate the former semantics without being impacted by divergent
      practice.  Over 10 years later, most user agents still do method
      rewriting for 301 and 302; therefore, this specification makes
      that behavior conformant when the original request is POST.

So note that this issue is not “xxx header is dropped”, but rather “non-safe methods are rewritten into GET on 301/302/303”, and this is intended behavior.

**Comment by brendo** [comment]
Thanks for your patience, I understand now, thanks!
