### ISSUE TITLE
Issue when minifying with webpack uglifyJS plugin

### ISSUE THREAD

**Issue by aweber1** [olalonde/follow-redirects#79]
Hi,

We're pulling in `follow-redirects` indirectly with a dependency on `axios`. Just recently, however, we're encountering an issue when trying to minify using webpack 2.x and it's built-in webpack.optimize.UglifyJsPlugin.

The specific error is: 
```
Unexpected token: punc (() [../~/follow-redirects/index.js:109,0]
```

Looking at the source for `index.js`, it appears that line 109 is using ES6 shorthand method definition syntax, which is causing the minifier in question to fail. I think we can work around it by either updating our webpack dependency or webpack uglify plugin dependency.

That said, just wanted to raise an issue here in the event you're not intending to publish with ES6 features or if someone else encounters the same.

**Comment by RubenVerborgh** [comment]
Oh, that's right… Well, since the resulting code is ES6 then, it would need to be transpiled first before going into UglifyJS. But I'll restore ES5 compatibility for now; not worth it for one line.

**Comment by RubenVerborgh** [comment]
…although I'm actually not sure why you would hit this problem. If you're using webpack, I'm assuming you're building for the browser. But why include `follow-redirects` in that build then? [The browser does redirects automatically.](https://github.com/olalonde/follow-redirects#browserify-usage)

Is this something specific to your configuration, or does axios do this in general?

**Comment by aweber1** [comment]
When the webpack target is `node`, axios will include `follow-redirects`: https://github.com/axios/axios/blob/master/lib/defaults.js#L16. And we use webpack to generate app bundles for browser and node (SSR).

Unfortunately, in general webpack configs using babel are not setup to transpile dependencies in the `node_modules` folder - though there are workarounds to do that for specific dependencies.

All of that said, the easiest solution (without any changes on your end), is to use the latest version of [`uglifyjs-webpack-plugin`](https://github.com/webpack-contrib/uglifyjs-webpack-plugin), which supports ES6+ targets. I tried this yesterday in our app and can confirm it addresses the original issue. The real problem being that the default uglify plugin doesn't work with ES6+.

To be completely fair, I don't think it's really an "issue" for `follow-redirects` to solve since the intended target for this lib is node 4+, for which transpilation to ES5 typically isn't necessary (at least not for shorthand methods).

But thanks also for the quick fix!
