### ISSUE TITLE
Following Javascript Bounces - e.g. onLoad => window.location = 'http://somewhere.else/...

### ISSUE THREAD

**Issue by qpongo** [olalonde/follow-redirects#81]
Before writing my own, I was looking for a library that handles all redirects and came across your project but it seems from my quick look at the code that **you don't handle all the various javascript redirects?**

Stuff like...

```
window.location = "https://www.example.com";
window.location.href = "https://www.example.com";
window.location.assign("https://www.example.com");
window.location.replace("https://www.example.com");
self.location = "https://www.example.com";
top.location = "https://www.example.com";

// Not in onclick, plus a bunch of other rules
```
> Contributing
> 
> Pull Requests are always welcome. Please file an issue detailing your proposal before you invest your valuable time. Additional features and bug fixes should be accompanied by tests.

**So, is this something that you'd want me to add?**

I'd prefer to add another dependency for the XRegExp library but think that I can do it without named parameters and negative look-behind.

I think that I also noticed some possible missing cases in <meta http-equivalent="refresh"

Please advise.

**Comment by RubenVerborgh** [comment]
> you don't handle all the various javascript redirects?

This library handles protocol-level redirects, i.e., HTTP status codes 3xx.

> 
> Stuff like...
> 
> window.location = "https://www.example.com";
> window.location.href = "https://www.example.com";
> window.location.assign("https://www.example.com");
> window.location.replace("https://www.example.com");
> self.location = "https://www.example.com";
> top.location = "https://www.example.com";

The only way to handle such redirects is by executing all JavaScript code on a page (and possibly loading external scripts).

> So, is this something that you'd want me to add?

Thanks for proposing, but this seems out of scope for this library. The size of the code needed for this is likely a multiple of the current follow-redirects size.

> I'd prefer to add another dependency for the XRegExp library but think that I can do it without named parameters and negative look-behind.

Nah, you need a full HTML parser and JavaScript engine :smile:

So thanks for proposing, but this seems more fit for a separate library.

**Comment by qpongo** [comment]
<head>
  <meta http-equiv="refresh" content="30">
</head>

**Comment by qpongo** [comment]
@RubenVerborgh 
> Nah, you need a full HTML parser and JavaScript engine ??
> 
> So thanks for proposing, but this seems more fit for a separate library.
> 

I respectfully disagree.  I'm only proposing a few lines of code, all done with regex -- no DOM required.  I've run it on more than 1 million sites at this point so....

I went ahead and used axios (which uses follow-redirects) and put my code on top of that so no worries.

REGARDING META REFRESH WITH LESS THAN A SINGLE DIGIT TIMER...
(this is one way that I've seen more than a few sites do redirection)

It seems to me that **you should be handling this one**, again with only regex.

```
<meta http-equiv='refresh' content='1;url=http://someotherdomain.com"
OR
<meta content='1;url=http://someotherdomain.com' http-equiv='refresh' 
```

The idea is that it waits for 1 second then jumps to another url = redirect

```
static getMetaBounce(html) {
    const REGEX_META_BOUNCE = XRegExp('<meta\\s+(?:http-equiv=[\'"]?refresh[\'"]?\\s+content=[\'"](?:\\d;)?url=(?<url>[^"\'>\\s]*)|content=[\'"](?:\\d;)?url=(?<url>[^"\'\\s]*)["\']\\s+http-equiv=[\'"]?refresh)');

    const metaBounce = XRegExp.exec(html, REGEX_META_BOUNCE);
    if (metaBounce && metaBounce.url) {
        return metaBounce.url;
    }
    return null;
}
```


And I don't need to use XRegExp but it's slightly less beautiful.

**Comment by RubenVerborgh** [comment]
> I respectfully disagree. I'm only proposing a few lines of code, all done with regex -- no DOM required. I've run it on more than 1 million sites at this point so....

While you might have found a regex that works on your 1 million sites, it is impossible to correctly parse HTML with only regular expressions in general. The expressivity of HTML is higher than what regex supports.

With JavaScript, it's even worse, as solving this problem can be reduced to the intractable halting problem.

For example, does your regular expression work for the following cases?

```javascript
// should detect redirect
(function (l) { l.href = "http://example.org/" })(window.location);
```

```javascript
// should NOT detect redirect
if (false) {
    window.location.href = "http://example.org/";
}
// window.location.href = "http://example.org/";
var self = { location: {} };
self.location.href = "http://example.org/";
throw new Error();
window.location.href = "http://example.org/";
```

```html
<div>
// should NOT detect redirect
window.location.href = "http://example.org/";
</div>
```

For the HTML case, your regex does not match the following valid case:

```html
<meta http-equiv=refresh content='0;URL=http://example.org/'>
```

Your regex will match the following invalid case:

```html
<noscript>
<meta http-equiv=refresh content='0;url=http://example.org/'>
</noscript>
```

And no matter how the regexes are adjusted, there will always be cases that are not covered, because of the expressivity mismatch. So we have the choice between either having incorrect support with regexes (which will lead to many frustrations and bug reports), or correct support with an HTML and JavaScript engine (which is way out of scope for this protocol-level library).

**Comment by qpongo** [comment]
Fair enough but...

#1.  I had dropped the window.location discussion after your first rebuke.  And, yes, I did run it successfully against the top 1M sites in Alexa.  [The main reason where this "javascript bounce" is used in the wild is with affiliate programs and I'm pretty confident that my logic works for all those as well as we test a million affiliate links per month.]

#2.  I still respectfully disagree that the <meta http-equiv=refresh case is too broad for regex OR not useful in a comprehensive "follow-redirects" project.   [BTW, I typed that regex by hand but 1 "?" is all it takes to correct the regex for the case which you said wasn't matched...

`<meta http-equiv=refresh content='0;URL=http://example.org/'>`

#3. Sorry, being picky now, but the <noscript> case isn't really invalid because there is no script engine.  :)

But I got it, you want to be protocol only so thanks for clearing that up.

_AND thanks for taking the time to respond and good luck with all your projects._

HAVE A GREAT WEEKEND...  ;)
