### ISSUE TITLE
PUT with redirects drops the request body

### ISSUE THREAD

**Issue by nodevar** [olalonde/follow-redirects#82]
Im heading over here from the Issue https://github.com/tejashah88/node-meraki-dashboard/issues/2 

In short, if i do PUT there is over redirects GET performed. Adding PUT to the SAFE_METHODS the body goes missing... i think.

I can see a few redirects while talking to the meraki API. 

>follow-redirects CURRENTREQUEST.output:  [ 'PUT /api/v0/networks/L_networkid/devices/serial HTTP/1.1\r\nx-cisco-meraki-api-key: apikey\r\ncontent-type: application/json\r\ncache-control: no-cache\r\npostman-token: d708deed-b15a-6af5-6ad5-38b83a074b12\r\nHost: dashboard.meraki.com\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n12',
  <Buffer 0d 0a>,
  '{"name":"TEST200"}',
  <Buffer 0d 0a> ] +3ms

So far so good, next message is: 

>follow-redirects redirecting to https://api.meraki.com/api/v0/networks/L_networkid/devices/serial PUT 307 +6s

Unfortunately next Message is GET: 
>follow-redirects redirecting to https://n192.meraki.com/api/v0/networks/L_networkid/devices/serial GET 308 +1ms

So it looks like when the redirect code is is not equal 307 and the method is not in the SAFE_METHODS list, GET is used.

As i put PUT in SAFE_METHODS list, the request is not anymore altered to GET, but i don't think the body/buffer is going through. Since i don't get back the updated object from the API.

Btw. talking direct to Host n192.meraki.com, PUT is executed and i get as response the updated object.

Can somebody help me point out this issue? How can i test that the body is still there, if PUT is in SAFE_METHODS and PUT is performed.

**Comment by RubenVerborgh** [comment]
> So it looks like when the redirect code is is not equal 307 and the method is not in the SAFE_METHODS list, GET is used.

Indeed, this is the behavior mandated by the [HTTP 1.1 specification](https://tools.ietf.org/html/rfc7231).

What is the status code returned by the server in your example?

**Comment by nodevar** [comment]
Hi Ruben

Yeah sure i agree that this has to be as you implemented it. And i dont think its about the status code (which is 302 by the way). 

But this  !(this._options.method in SAFE_METHODS) will always be false since the SAFE_METHODS list looks like: 

var SAFE_METHODS = { PUT: true, GET: true, HEAD: true, OPTIONS: true, TRACE: true }; 

The Keys should be written in lowercase, because this._options.method returns the values in lowercase. 
after the following if works and will no longer reset the bodyBuffer:

`
if (response.statusCode !== 307 && !(this._options.method in SAFE_METHODS)) {
      this._options.method = "GET";
      // Drop a possible entity and headers related to it
      this._requestBodyBuffers = [];
      for (header in headers) {
        if (/^content-/i.test(header)) {
          delete headers[header];
        }
      }
    }
`

**Comment by RubenVerborgh** [comment]
> And i dont think its about the status code (which is 302 by the way).

Yes, it is about the status code:

> > Note: For historical reasons, a user agent MAY change the request
      method from POST to GET for the subsequent request.  If this
      behavior is undesired, the 307 (Temporary Redirect) status code
      can be used instead.

—https://tools.ietf.org/html/rfc7231#section-6.4.3

> But this !(this._options.method in SAFE_METHODS) will always be false

No, we have [100% branch coverage](https://coveralls.io/github/olalonde/follow-redirects) so the `true` condition is definitely triggered. Try lowercasing them and you'll see that 12 tests fail.

> The Keys should be written in lowercase, because this._options.method returns the values in lowercase.

No, HTTP method names are case-sensitive:

> > The method token is case-sensitive because it might be
   used as a gateway to object-based systems with case-sensitive method
   names

—https://tools.ietf.org/html/rfc7231#section-4.1

`this._options.method` simply contains the original method, which should be uppercase to match HTTP casing (see examples in the [Node.js documentation](https://nodejs.org/api/http.html#http_message_method)).

So what you are seeing is intended behavior. The servers needs to use 307 if the request may be repeated with the same method.

**Comment by nodevar** [comment]
Thank you Ruben.

Indeed i see lowercase methods.
`
debug("response.statusCode: ", response.statusCode, "this._options.method : ", this._options.method, "SAFE_METHODS: ", SAFE_METHODS, "this._options.method in SAFE_METHODS: ", (this._options.method in SAFE_METHODS));
`

> follow-redirects response.statusCode:  302 this._options.method :  get SAFE_METHODS:  { PUT: true, GET: true, HEAD: true, OPTIONS: true, TRACE: true } this._options.method in SAFE_METHODS:  false +0ms

For others, this is seen with the axios library. If i use native node.js requests this is not the case at all.

**Comment by RubenVerborgh** [comment]
> For others, this is seen with the axios library.

That seems like a bug in Axios (also appeared in #73); I'd suggest filing it with them.
