### ISSUE TITLE
POST request is changed to GET after redirect

### ISSUE THREAD

**Issue by jeroencouwenberg** [olalonde/follow-redirects#83]
Hi,

I am trying out the follow-redirects library to overcome redirects I get when calling a certain endpoint. After implementing the follow-redirects library the redirects are handled automatically for GET, DELETE and PUT requests that are sent by my nodejs script so that is great! But somehow the POST requests are failing. The endpoint I am calling returns a response indicating that GET is not allowed. Which makes sense because a POST is expected. So it seems that somehow the POST requests are turned into GET requests after the redirect. Could you please help me out? 
Please find more information below.

Please find attached a TXT containing a snippet of the code. A little explanation is perhaps required: the javascript is developed so that it can function as a proxy. So my web client sends all needed information to the nodejs script. The nodejs script creates a http request from that information and returns the response.

[follow-redirects-javascript-sample.txt](https://github.com/olalonde/follow-redirects/files/1768727/follow-redirects-javascript-sample.txt)

**Comment by RubenVerborgh** [comment]
> So it seems that somehow the POST requests are turned into GET requests after the redirect.

This happens because the HTTP spec states:

> > Automatic redirection needs to done with
   care for methods not known to be safe, as defined in Section 4.2.1,
   since the user might not wish to redirect an unsafe request.

—https://tools.ietf.org/html/rfc7231#section-6.4

Specifically, for 301/302/303 responses, non-safe methods are changed into `GET`. Only 307 explicitly tells the client that reusing the same method is allowed.

**Comment by JayantNayak** [comment]
Hi RubenVerborgh,

After going through your answer I finally get it why my POST requests were getting changed to GET.
Is there any way to overcome this if  for response code  301/302/303 responses, non-safe methods ?
I know this may sound foolish but its one of my requirements.

I also have a simillar proxy server .
https://stackoverflow.com/questions/51485350/post-method-for-http-redirect-not-working-in-nodejs
Please let me know if you can help me here.

Regards,
Jayant

**Comment by RubenVerborgh** [comment]
@JayantNayak We could provide this as an option. Which status code(s) do you want to redirect from? Could you give me an example of the current redirection flow?

**Comment by JayantNayak** [comment]
Hi RubenVerbogh,

I am using  open odata v4 service  which you can find it here
https://www.odata.org/odata-services/

And currently I am using the TripPinRESTierService . If you see the urls provided here are all of type 
**https** and its seems to work fine as long as I am performing the modify operations using https urls.
But as soon as I change the url/ protocol to http it gives me redirection status code **301** , status message **Moved Permanently** in nodejs .  On retriggering the same using http urls works  fine on any restclient like Postman . 
url - http://services.odata.org/TripPinRESTierService/(S(3mslpb2bc0k5ufk24olpghzx))/People
body - 
```
{
    "UserName":"lewisblack",
    "FirstName":"Lewis",
    "LastName":"Black",
    "Emails":[
        "lewisblack@example.com"
    ],
    "AddressInfo": [
    {
      "Address": "187 Suffolk Ln.",
      "City": {
        "Name": "Boise",
        "CountryRegion": "United States",
        "Region": "ID"
      }
    }
    ]
}
```

The nodejs code is as follows,

```
"use strict";
var express = require("express");
var app = express();
const http = require("http");
var bodyParser = require("body-parser");
var followRedirects = require('follow-redirects');
app.use(bodyParser.json());


  function pipeResponse (source, sink) {

    console.log("***********Response ***************");

    console.log("->>statusCode "+source.statusCode);
    console.log("->>statusMessage "+source.statusMessage);

    sink.statusCode = source.statusCode;
    sink.statusMessage = source.statusMessage;

    console.log("----------Response Headers ---------");

    Object.keys(source.headers).
        forEach((name) => {

            console.log(name+" : "+source.headers[name]);
            sink.setHeader(name, source.headers[name]);
        });
    console.log("-------------------------------------");   

    source.on("data", (ce) => {
        sink.write(ce);
        console.log("data  present" );
    });
    source.on("end", () => sink.end());

    console.log("**************************************");

}

// used to handle both query/read and modify operations on entityset people
app.all("/api/people", (req, res) => {

    // sample service 
    var options = {"headers": {}};
    options.host = "services.odata.org";
    options.path = "/TripPinRESTierService/(S(3mslpb2bc0k5ufk24olpghzx))/People";
    options.method = req.method;
    console.log("request method type " + req.method);

    if(req.headers["content-type"]){     
        options.headers["content-type"] = req.headers["content-type"];
    }

    var payLoad ;
    payLoad = req.body;
    //var proxyRequest = followRedirects.http.request(options, (backendres) => pipeResponse(backendres, res));
    var proxyRequest = http.request(options, (backendres) => pipeResponse(backendres, res));
    proxyRequest.on("error", (err) => {

        console.error("request failed",err);

    });
    if (payLoad) {
        console.log("payload data " + JSON.stringify(payLoad));
        proxyRequest.write(JSON.stringify(payLoad));
    }

    proxyRequest.end();


});

app.listen(8080, () => {
});
```


Regards,
Jayant

**Comment by RubenVerborgh** [comment]
For a 301, I'm afraid our hands are tied:

> If the 301 status code is received in response to a request other
> than GET or HEAD, the user agent MUST NOT automatically redirect the
> request unless it can be confirmed by the user, since this might
> change the conditions under which the request was issued.
> 
> Note: When automatically redirecting a POST request after
> receiving a 301 status code, some existing HTTP/1.0 user agents
> will erroneously change it into a GET request.
—https://tools.ietf.org/html/rfc2616#section-10.3.2

Note that it says `MUST NOT` (instead of `SHOULD NOT`), so this means we are not allowed to do it. In other words, OData must fix their service.

Question is: should follow-redirects allow developers to break compatibility with the HTTP spec? I'm inclined to say no, but open to other arguments.

**Comment by JayantNayak** [comment]
Hi RubenVerborgh,

I think you are obeservations are correct and we should stick to the HTTP specs instead of going
against it.
Thanks for quick discussions we had, lot my doubts were cleared . 👍 
You may now close this question.

Regards,
Jayant

**Comment by RubenVerborgh** [comment]
Thanks!

**Comment by mvandervliet** [comment]
@RubenVerborgh 

> Question is: should follow-redirects allow developers to break compatibility with the HTTP spec? I'm inclined to say no, but open to other arguments.

Let me first say that I appreciate a rigid stance on adhering to a specification. That said, I also have an appreciation for packages that take a "standards by default" approach, while also supporting options that enable certain deviations. 

In a perfect world, every service would be implemented _exactly_ to specification. However in reality, this is simply not the case, and environmental conditions may often exacerbate such problems. For this reason, I would recommend support for an option to follow and preserve original non-GET methods.

**Comment by RubenVerborgh** [comment]
@mvandervliet It's a MUST NOT though, so pretty strong. But open to a PR.
