### ISSUE TITLE
Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by tifroz** [olalonde/follow-redirects#84]
I am seeing occasional crashes (see stack trace below). Looking at the code, I am not seeing how there could be a confusion between the `http` client vs the `https` agent since `nativeProtocol ` takes its cue directly from the request's options.

Any idea?

```
Error: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:131:11)
    at Object.request (http.js:38:10)
    at Object.request (https.js:239:15)
    at RedirectableRequest._performRequest (/opt/vproxy/node_modules/follow-redirects/index.js:73:20)
    at RedirectableRequest._processResponse (/opt/vproxy/node_modules/follow-redirects/index.js:158:8)
    at ClientRequest.RedirectableRequest._onNativeResponse (/opt/vproxy/node_modules/follow-redirects/index.js:42:8)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
```

For reference, here is the block of code that crashes

```
RedirectableRequest.prototype._performRequest = function () {
	// If specified, use the agent corresponding to the protocol
	// (HTTP and HTTPS use different types of agents)
	var protocol = this._options.protocol;
	[...]

	// Create the native request
	var nativeProtocol = nativeProtocols[protocol];
	var request = this._currentRequest =
				nativeProtocol.request(this._options, this._onNativeResponse); // >>> THIS LINE CRASHES
	this._currentUrl = url.format(this._options);
```

**Comment by RubenVerborgh** [comment]
> I am seeing occasional crashes

What's your code? I'm suspecting you are injecting a custom `agent`?

When you do so, you need to inject different agents for HTTP and HTTPS, as [documented here](https://github.com/olalonde/follow-redirects#per-request-options):
```javascript
{ agents: { http: new http.Agent(), https: new https.Agent() } }
```

**Comment by tifroz** [comment]
Gee I feel dumb for overlooking this!  You are right, my code looked like the code below. I am making the change & testing overnight. Thanks, I will post an update to confirm tomorrow!

```
function sniSelect = function(hostname, callback) {
//...
}
opts = {
			SNICallback: sniSelect,
			agent:  new http.Agent()
}
server = https.createServer( opts, function(req, res){...})
```

**Comment by RubenVerborgh** [comment]
Okay, thanks!

**Comment by tifroz** [comment]
Yes, confirmed: your diagnosis nailed it (though I initially targeted the wrong code...in hindsight I have no idea what this `agent` parameter was doing in my `createServer` call...)

Thank you again!
