### ISSUE TITLE
RedirectableRequest.prototype.write emits unintuitive error if data is the wrong type

### ISSUE THREAD

**Issue by georgezzhang** [olalonde/follow-redirects#87]
Is `data` in the `RedirectableRequest.prototype.write` (https://github.com/olalonde/follow-redirects/blob/master/index.js#L59) method signature meant to be a String or Buffer only?

I had a case where some data passed in to this function through `axios` was a boolean, resulting in `data.length` evaluating to `undefined`, and `this._requestBodyLength + data.length <= this._options.maxBodyLength` evaluating to `false`. The error emitted in this case was "Request body larger than maxBodyLength limit", which was not actually the problem. Is it worth type-checking `data` and emitting a different error if it's not the proper type?

Thanks!

**Comment by RubenVerborgh** [comment]
> Is data in the RedirectableRequest.prototype.write (https://github.com/olalonde/follow-redirects/blob/master/index.js#L59) method signature meant to be a String or Buffer only?

Yes:

>> For streams not operating in object mode, chunk must be a string, Buffer or Uint8Array.

— https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback

> I had a case where some data passed in to this function through axios was a boolean,

Yeah, axios kind of has a history of passing non-standard things to this library 😄 (#73, #74, #82).

> Is it worth type-checking data and emitting a different error if it's not the proper type?

It makes sense, yes.
