### ISSUE TITLE
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

### ISSUE THREAD

**Issue by orzFly** [olalonde/follow-redirects#97]
For example, if a response redirected to something like `http://localhost/：.torrent`, an error will be raised here https://github.com/olalonde/follow-redirects/blob/master/index.js#L157.

**Comment by orzFly** [comment]
I am currently working on a PR :)

**Comment by RubenVerborgh** [comment]
Well we should probably first discuss the desired behavior then 😄

**Comment by RubenVerborgh** [comment]
I think we want an error event instead.

**Comment by orzFly** [comment]
Yes, I am going to try catch the call to nativeProtocol.request to prevent future errors. If it fails, emit an error and abort the whole things.

**Comment by orzFly** [comment]
I am sorry to say but I found the problem doesn't exist in follow-redirects any more. I was using axios' `^1.3.0`. This is already fixed in `1.5.9`.

I think I'd better to ask axios to upgrade dependency instead.

**Comment by Strate** [comment]
@orzFly, how you resolved this issue? I am using latest axios now, which uses 1.5.10 version of this library, and I am faced to exactly same issue.
